source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

workspace 'TimeZonePickerExample'

target :'TimeZonePickerExample' do
    project 'TimeZonePickerExample.xcodeproj'
    platform :ios, '8.0'

    pod 'TimeZonePicker'
end
